# Site settings
title: Martin Trapp
email: martin.trapp@aalto.fi
description: >- # this means to ignore newlines until "baseurl:"
  Academic website for Martin Trapp.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar

# Collections
collections:
  news:
    output: false
    sort_by: date
  research:
    output: false
  technical_notes:
    output: true
    sort_by: date
    permalink: /notes/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "technical_notes"
    values:
      layout: "note"

# Academic info
author:
  name: Martin Trapp
  title: AoF Postdoctoral Researcher
  affiliation: Aalto University, Finland
  email: firstname.lastname@aalto.fi
  office: "Computer Science Building"
  bio: >-
    Martin is an Academy of Finland postdoctoral researcher at Aalto University and a member of the ELLIS society. 
    My research is centred around representing, quantifying, and reducing uncertainties to make machine learning more reliable. 
    I am particularly interested in efficient and principled approaches for large-scale systems with applications in language and vision.

# Social links
social:
  google_scholar: "https://scholar.google.com/citations?user=GwCrZP4AAAAJ"
  orcid: "https://orcid.org/0000-0000-0000-0000"
  linkedin: "https://linkedin.com/in/martintrapp"
  bluesky: "https://bsky.app/profile/martintrapp.bsky.social"
  github: "https://github.com/janesmith"

# Jekyll Scholar configuration
scholar:
  style: apa
  locale: en
  source: _bibliography
  bibliography: publications.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  query: "@*"
  group_by: year
  group_order: descending
  sort_by: year
  order: descending
  details_dir: ""
  details_layout: ""
  details_link: ""

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
